### ISSUE TITLE
Grass is always twice the given length

### ISSUE THREAD

**Issue by seanofw** [Thoof/aseprite-grassify#1]
Hi, neat script!  I thought I'd give it a try, so I sketched up this grass sample, but every time I use it, the grass it produces is always really tall, instead of the smoother shapes in your demo, as in the recording below.  Is there a bug in the version of the code posted on GitHub?

![grassify-bug-1](https://user-images.githubusercontent.com/981716/157128350-0aa6f8ef-ad04-403f-a533-fa6d9de5ef98.gif)

I tried it in both Aseprite 1.2.28 and 1.3.0-beta11, and it produces the same results in both.

**Comment by Thoof** [comment]
Hi sean, 
In my example I've got the grass separated by layer. The script is mostly intended to be used on isolated clusters of pixels, either by selection or by layer. I'll keep this open since it'd be nice to figure out how to apply it across the whole cel.

**Comment by Thoof** [comment]
Grass length should be working as intended now on layers/selections with multiple colors.
