### ISSUE TITLE
Fails on indexed-color images

### ISSUE THREAD

**Issue by seanofw** [Thoof/aseprite-grassify#2]
On indexed-color images, Grassify seems to get the spacing wrong, and produces blocky, 4-pixel outputs, like in the recording below.

![grassify-bug-2](https://user-images.githubusercontent.com/981716/157128850-35190812-f183-42f2-8829-c86d5ef848d1.gif)

Tested in Aseprite 1.2.28 and 1.3.0-beta11, and it produces the same result in both.

**Comment by Thoof** [comment]
Thanks for testing, that's some wonky behavior. Will look into it soon

**Comment by Thoof** [comment]
Should be working now, as of the last commit.
